// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyJDg3OXTHg0myzrci8YM6D_fvBi5HQms',
    appId: '1:117093957120:web:fe2a64e85729121c9d22e5',
    messagingSenderId: '117093957120',
    projectId: 'nasa-e1e15',
    authDomain: 'nasa-e1e15.firebaseapp.com',
    storageBucket: 'nasa-e1e15.appspot.com',
    measurementId: 'G-56P8DKZF00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMEBXG_wULxv_gXK-E8uFvF9iecKlMrXI',
    appId: '1:117093957120:android:d5c7afdc9d7d66689d22e5',
    messagingSenderId: '117093957120',
    projectId: 'nasa-e1e15',
    storageBucket: 'nasa-e1e15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsRX7XCcvJtBEJiw-gInaewMwLGiAvNcQ',
    appId: '1:117093957120:ios:2b70ba94643d93769d22e5',
    messagingSenderId: '117093957120',
    projectId: 'nasa-e1e15',
    storageBucket: 'nasa-e1e15.appspot.com',
    iosBundleId: 'com.example.nasa',
  );
}
