// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp53Lzrkcs7RDEdq1SqpYx2uN6S2tzj7c',
    appId: '1:622713575848:web:657ca7d241134ef907a59d',
    messagingSenderId: '622713575848',
    projectId: 'seko-aa05c',
    authDomain: 'seko-aa05c.firebaseapp.com',
    storageBucket: 'seko-aa05c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX8dnnO3sKyXCqyRY9ZfUtJQL5MM4Q4So',
    appId: '1:622713575848:android:a01df4b34ae87f1f07a59d',
    messagingSenderId: '622713575848',
    projectId: 'seko-aa05c',
    storageBucket: 'seko-aa05c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcJIlTW9ps15hIufMKx7Tnh3Q46jcwPCk',
    appId: '1:622713575848:ios:4319ca733b592da607a59d',
    messagingSenderId: '622713575848',
    projectId: 'seko-aa05c',
    storageBucket: 'seko-aa05c.appspot.com',
    iosBundleId: 'com.example.seko',
  );

}